// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy4rSDWHYb2nkdzh12PWR46jSF-qS-6Gc',
    appId: '1:466101939568:web:d568a0fd6de87608b933b5',
    messagingSenderId: '466101939568',
    projectId: 'rentapp2024',
    authDomain: 'rentapp2024.firebaseapp.com',
    storageBucket: 'rentapp2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqE3dZfmwHco4Z3R0RNzW-xWbWvZGOxCo',
    appId: '1:466101939568:android:07e0d3e2d3614c60b933b5',
    messagingSenderId: '466101939568',
    projectId: 'rentapp2024',
    storageBucket: 'rentapp2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx_r8fWMnOQMYtM1c677hDLlqlHJEsZyU',
    appId: '1:466101939568:ios:529a136aea5d492ab933b5',
    messagingSenderId: '466101939568',
    projectId: 'rentapp2024',
    storageBucket: 'rentapp2024.appspot.com',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx_r8fWMnOQMYtM1c677hDLlqlHJEsZyU',
    appId: '1:466101939568:ios:529a136aea5d492ab933b5',
    messagingSenderId: '466101939568',
    projectId: 'rentapp2024',
    storageBucket: 'rentapp2024.appspot.com',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy4rSDWHYb2nkdzh12PWR46jSF-qS-6Gc',
    appId: '1:466101939568:web:b13b6052d37c5657b933b5',
    messagingSenderId: '466101939568',
    projectId: 'rentapp2024',
    authDomain: 'rentapp2024.firebaseapp.com',
    storageBucket: 'rentapp2024.appspot.com',
  );
}
